data_dir: ${BASE_DIR}/data/Ultrasound-Breast-Image
sd_ft_augmented_dir: ${BASE_DIR}/data/augmented_finetuned_sd
vae_augmented_dir: ${BASE_DIR}/data/augmented_vae
controlnet_ft_augmented_dir: ${BASE_DIR}/data/augmented_finetuned_controlnet
output_dir: ${BASE_DIR}/model/output
wandb_key: ${WANDB_KEY}
model:
  baseline: baseline_model.pth
  regular: reg_augmentation_model.pth
  stable_diffusion: stable_diffusion_model.pth
  control_net: control_net_model.pth
  vae: vae_model.pth

vae:
  latent_dim: 128
  num_classes: 3
  input_channels: 3
  batch_size: 16
  num_epochs: 100