data_dir: '/home/danielchoi/BreastCancerControlNet/data/Ultrasound-Breast-Image'
output_dir: '/home/danielchoi/BreastCancerControlNet/model/output'
wandb_key: "9172fb113e07d174f618e9042047cc5c4adacc0f"
model:
  baseline: baseline_model.pth
  regular: reg_augmentation_model.pth
  stable_diffusion: stable_diffusion_model.pth