data_dir: "/home/danielchoi/BreastCancerControlNet/data/Ultrasound-Breast-Image"
augmented_dir: "/home/danielchoi/BreastCancerControlNet/data/augmented_vae"

latent_dim: 128
num_classes: 3
input_channels: 3
batch_size: 16
num_epochs: 100